labels:

  # - name: invalid
  #   labeled:
  #     issue:
  #       body: Please follow the issue templates.
  #       action: close
  #     pr:
  #       body: Please follow the pull request templates.
  #       action: close
  #   unlabeled:
  #     issue:
  #       body: Thank you for following the template. The repository owner will reply.
  #       action: open
  # - name: forum
  #   labeled:
  #     issue:
  #       body: |
  #         Please ask questions about GitHub Actions at the following forum.
  #         https://github.community/t5/GitHub-Actions/bd-p/actions
  #       action: close
  # - name: wontfix
  #   labeled:
  #     issue:
  #       body: This will not be worked on but we appreciate your contribution.
  #       action: close
  #   unlabeled:
  #     issue:
  #       body: This has become active again.
  #       action: open
  # - name: duplicate
  #   labeled:
  #     issue:
  #       body: This issue already exists.
  #       action: close
  # - name: good first issue
  #   labeled:
  #     issue:
  #       body: This issue is easy for contributing. Everyone
  
  - name: integration: utility_meter
    labeled:
      issue:
        body: |
        A little helping hand, here are links to the docs.
        https://www.home-assistant.io/integrations/utility_meter/
